### PR TITLE
Support for Comments

### PR DESCRIPTION
**Pull request by patcable**
This adds support for reviewer comments (#14). Reviews now have a field for adding a comment along with the scoring. It looks something like this:
judycomment

To give the best at an untainted submission review, I moved the list of comments to the "scores" page:
clist.

### CODE REVIEW

**Comment by obfuscurity** [comment]
I haven't had a chance to really dig into this yet but at a glance it looks fine. How does it treat empty/null comments?

**Comment by patcable** [comment]
Null comments are fine, score is still logged. Forgot to kill off the null comments in the scoring view, but fixed that in 2d0a1c8.

**Comment by obfuscurity** [comment]
You're using this now for DoD Boston?

**Comment by patcable** [comment]
nope -- LISA16 (but in Boston this year)

**Comment by obfuscurity** [comment]
Oh, one thing I'd add if you have time/interest... something like `text-overflow: ellipsis` (https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) for limiting the number of characters in the score/comment view. What's the current behavior?

**Comment by obfuscurity** [comment]
Note that I'm happy to bring it in as is... didn't mean to sound greedy or demanding. I'm really grateful for the contribution here. :heart:

**Comment by patcable** [comment]
Oh not a problem -- just wanted to see what the current behavior was before responding. Currently, long winded commenters are just going to wrap and span the whole container (from score to the right edge of the sessions button). Might try and play with paragraph formatting in a few.

**Comment by patcable** [comment]
Yeah, I wasn't quite sure how to fix the long span. I don't think our reviewers are going to go too crazy (famous last words) -- but also, my css-fu is a bit weak to get everything working a way that would look better. Future work? :)

**Comment by obfuscurity** [comment]
Yeah, no problem.

**Comment by obfuscurity** [comment]
Thanks again :cake: 🍦

**Pull request merged**
